js/id/ui/coordinates.js
Added parenthesis after parseInt so the hundredths will show
=> So hundredths will show

js/hoot/control/Conflicts.js, js/hoot/control/View.js
use layerRemove event listener to keep code contained in
control/Conflicts.js
=> #7152, set reviewIds to null when layer removed or review complete

js/id/renderer/map.js, js/id/ui/map_in_map.js
Map-in-map doesn't always redraw after main map pans/zooms
=> #9 Map-in-Map redraw

js/hoot/control/utilities/Folder.js
=> Unselected datasets will have no context menu

js/hoot/tools.js
https://github.com/ngageoint/hootenanny-ui/issues/63
=> Layer color = green if entering review mode

js/hoot/control/Conflicts.js
* Not required since density raster has been removed
=> Removing zoom behavior

js/hoot/control/Conflicts.js, js/hoot/tools.js
* Change color to green when entering review mode
* Zoom to review
=> UI Review Issues

js/hoot/control/Conflicts.js
=> Zooms to entity during review

js/id/ui/raw_membership_editor.js, js/id/ui/raw_tag_editor.js
* Also fixed bug where unprotected tags were not being deleted
=> Users cannot edit 'reviewee' relation

js/hoot/control/Export.js, js/hoot/control/utilities/Dataset.js, test/spec/hoot/model/Import.js
=> Remove '(Hootenanny Default)' from translations

js/hoot/control/Conflicts.js
=> Min zoom on review change is now 18

js/hoot/control/Conflate.js, js/hoot/control/utilities/Dataset.js, js/hoot/control/utilities/Folder.js, js/hoot/model/Folders.js
* Duplicate folder names at same level (ngageoint/hootenanny-ui#85)
* Dataset/Folder icons not clickable (ngageoint/hootenanny-ui#83)
* Context menu for folders not working (ngageoint/hootenanny-ui#88)
=> Fixed folder issues

data/core.yaml, dist/locales/en.json, js/hoot/control/Conflicts.js, js/hoot/model/Conflicts.js, js/id/renderer/arrow_layer.js
@sisskind @bwitham Will you guys comment on the changes and merge?
=> Enable bi-directional POI merge tool

js/hoot/control/utilities/Folder.js, js/hoot/model/Folders.js, js/hoot/view/utilities/Dataset.js
* Can delete closed folder (ngageoint/hootenanny-ui#92)
* Folders are now case sensitive (ngageoint/hootenanny-ui#91)
* Modify folder name does not allow duplicates
=> Corrected folder issues

js/hoot/control/utilities/Folder.js
=> Folder icon will toggle open/closed

js/id/core/connection.js
=> Changed 'view' to 'edit' in warning

js/hoot/control/utilities/Dataset.js
=> Clipped dataset now saves output name

js/hoot/control/Conflate.js, js/hoot/control/Control.js, js/hoot/control/Export.js, js/hoot/control/utilities/Dataset.js, js/hoot/control/utilities/Folder.js
=> Input forms detect invalid input values

js/hoot/control/utilities/Dataset.js, js/hoot/model/rest.js
* Clipped dataset will take placeholder value if nothing new added
* Clipped dataset now going to correct folder destination
=> Clipped Dataset Save Issues

js/hoot/control/Conflicts.js, js/hoot/control/conflicts/map/FeatureHighlighter.js, js/hoot/control/conflicts/map/FeatureNavigator.js, js/id/renderer/map.js
Was caused by not having code to hightligh relation members
=> Multiline Relation does not show "blue" feature #122

js/id/ui/tools.js
=> Clip tool removed in review mode

js/hoot/view/utilities/Dataset.js
* d3.event.x --> d3.event.clientX
* #121
=> Bulk Import in Firefox

js/hoot/control/conflate/advanced_options/SelectionRetriever.js, js/id/ui/help.js
=> Updated to take value if entered over default value

js/id/ui/info.js
* Updated from iD Editor code base
=> Measurement tool area perimeter fix

css/app.css
=> Edit feature sidebar fully visible

js/hoot/control/utilities/Dataset.js
=> FileGDB default name correction

js/hoot/control/utilities/Dataset.js, js/hoot/control/utilities/Folder.js
=> Modify name maintains title before edit

js/hoot/control/utilities/Dataset.js
* #232 Export Dialog
* #222 Clip Tools
=> Updated output text field

js/hoot/control/Validation.js, js/hoot/tools.js, js/id/core/connection.js, js/id/id.js
To test, run Prepare for Validation on a dataset and then add the dataset to the map.  The UI should prompt the user to enter the imagery validation workflow.
The choice buttons should then set certain tags on the validated feature and proceed to the next review item.  As validation review items are resolved, the relation is deleted.  After all items are handled, the dataset should have no more review relations.  These should be removed:
```
<relation visible="true" id="1" timestamp="2016-02-12T15:30:50Z" version="1" changeset="163">
<member type="node" ref="29" role="reviewee"/>
<tag k="hoot:review:type" v="Validation"/>
<tag k="hoot:review:needs" v="yes"/>
<tag k="hoot:review:choices:1" v="{&quot;label&quot;:&quot;Confirmed&quot;,&quot;description&quot;:&quot;You can look at the point …
```
=> #229 Fix imagery validation ui code for reviews as relations

js/id/ui/map_data.js
=> Line width adjustment limited to path.way

css/app.css, js/id/ui.js, js/id/ui/coordinates.js
=> DD, UTM Coordinate Display

js/hoot/control/utilities/BasemapDataset.js
=> On basemap publish, spinner appears

js/hoot/control/utilities/Folder.js, js/id/ui.js
=> Updated limit on dataset text

data/core.yaml
Reverts ngageoint/hootenanny-ui#245
Error when making within core.yaml
=> Revert "Updated core.yaml"

js/id/core/connection.js
=> Added return statement to redraw map

js/hoot/control/utilities/Folder.js
* ngageoint/hootenanny-ui#260
* selectedLayerIDs will get reset on context menu selection
=> Context menu shows correct # of selected datasets

js/id/ui/entity_editor.js, js/id/ui/preset_list.js, js/id/util.js
=> Added customTranslation service

js/hoot/control/utilities/Folder.js
@sisskind Please make sure the fix does not break your original intention.
=> Right-click menu display issues #273

js/id/ui/raw_tag_editor.js
#266 
@mattjdnv Entity editor tags should now be sorted alphabetically.  Feel free to test out.
=> Entity tag values sorted a-z

data/hootConfig.json
=> Tightened MaxLevDistance for better results

css/style2.css, js/hoot/tools.js
These other two commits 459ed828fff704f172b11aea5da76ff5b49a792f and
a24085225b8874f7e13def2bd104a1466aa7c751 from @mjeffe98 list appear to have already been merged.
=> Release patches from develop branch

js/id/ui/entity_editor.js, js/id/ui/preset_list.js, js/id/util.js
Related to following tickets:
* #280 
* #265 
* #203 
All are changes that should be included in version 0.2.23
=> Entity editor patch for release

js/id/ui/preset/combo.js
=> Preset comboboxes alphabetized

js/hoot/view/VersionInfo.js, js/hoot/view/utilities/About.js
#297 
Enhanced the VersionInfo.js code and created calls from About.js to reduce code reuse.
=> About.js uses VersionInfo.js code

js/hoot/model/Conflicts.js
=> #256 Unmerged features no longer white

js/hoot/control/conflicts/map/FeatureHighlighter.js
=> FeatureHighlighter will ensure entities exist.

js/id/ui/map_data.js
* Cannot have line width less than 0 or greater than 25
=> #331 Line Width Bounds

js/hoot/Hoot.js
=> No spaces allowed in dataset name

data/core.yaml, data/operations-sprite.json, dist/locales/en.json, index.html, js/id/operations/toggle.js, js/id/ui/radial_menu.js
=> #321 Toggle Layers added to radial menu

js/id/ui/background.js
=> Brightness update

index.html, js/hoot/control/conflicts/map/FeatureHighlighter.js, js/id/modes/select.js
#338 Remove flashing features
@treycaldwell @brianhatchl can one of you review?
=> Remove flashing features

js/id/ui/map_data.js
=> Line width adjustment also adjusts shadow, casing

css/hoot-style.css, index.html, js/hoot/control/Conflicts.js, js/hoot/control/conflicts/actions/PoiMerge.js, js/hoot/control/conflicts/actions/TraverseReview.js, js/hoot/control/conflicts/map/FeatureHighlighter.js, js/hoot/model/Layers.js, js/id/actions/review.js, js/id/operations/review.js, js/id/renderer/background.js, js/id/renderer/map.js, js/id/renderer/review_layer.js
=> Merging #264 with develop

js/hoot/model/Conflicts.js, js/hoot/model/Layers.js, js/hoot/view/utilities/ReviewBookmarks.js
#356 
Also may mitigate ngageoint/hootenanny#501
=> #356 Alert user that deleting layer will delete bookmarks

data/core.yaml, dist/locales/en.json, js/id/renderer/map.js, js/id/ui/map_data.js, js/id/ui/modes.js
=> Enable snap moved to toggle in Map Data

js/id/modes/measure_add_area.js, js/id/modes/measure_add_line.js, js/id/ui/tools.js
When exiting measure mode, the Tools button is replaced by "Clear" which removes measurement vectors.
=> Clear replaces Tools when measuring

js/id/core/connection.js, js/id/id.js, js/id/renderer/map.js, js/id/ui/raw_tag_editor.js, test/index.html, test/spec/core/connection.js, test/spec/hoot/controller/import.js, test/spec/hoot/model/Export.js, test/spec/modes/add_point.js
=> fix and enable remaining mocha tests

.gitignore, js/id/ui/confirm.js, package.json, test/index.html
=> Generate code coverage report for mocha tests

js/hoot/control/translation_assistant.js, js/hoot/ui/HootFormFgdbExportMenu.js, js/hoot/ui/HootFormReviewmarkMenu.js, js/id/ui/tools.js
=> Remove offsetParent

js/hoot/Hoot.js
=> TA needs context to avoid this error

js/hoot/model/Conflicts.js
=> let change tags update the feature, don't do it in javascript #416

js/id/operations/review.js
=> #431 GoTo Review for Ways

js/hoot/Hoot.js, js/hoot/control/conflicts/map/FeatureNavigator.js
New function checks for valid coordinates when panning to entity.
@brianhatchl can you take a quick look -- should be an easy one.  Thanks.
This is a potential mitigation for #424, but will need to replicate the error to fully confirm.
=> Check for valid coordinates

js/hoot/model/Layers.js
Will be merged following approval of ngageoint/hootenanny#501
=> Services will handle bookmark deletion

js/hoot/control/conflicts/actions/TraverseReview.js, js/hoot/control/conflicts/map/FeatureHighlighter.js, js/id/ui/entity_editor.js
also only call highlightLayer if edited feature belongs to review
=> #496, eliminate loc, always pass panTo param

data/presets/presets/mgcp/AL010.json, data/presets/presets/mgcp/AL015.json, data/presets/presets/mgcp/AL020.json, data/presets/presets/mgcp/AL099.json, data/presets/presets/mgcp/AL105.json, data/presets/presets/mgcp/AN010.json, data/presets/presets/mgcp/AP010.json, data/presets/presets/mgcp/AP030.json, data/presets/presets/mgcp/AP050.json, data/presets/presets/mgcp/AQ040.json, data/presets/presets/mgcp/AQ065.json, data/presets/presets/mgcp/BH030.json, data/presets/presets/mgcp/BH070.json, data/presets/presets/mgcp/BH140.json, data/presets/presets/mgcp/GB005.json, data/presets/presets/tdsv40/AL105.json, data/presets/presets/tdsv61/AL105.json, js/id/ui/preset_list.js
1. refs #487 
This is now based on Develop instead of Master.
=> Re-do the new MGCP presets

.gitignore, css/hoot-style.css, js/hoot/control/conflicts/actions/TraverseReview.js, js/hoot/control/conflicts/info/ReviewTable.js, js/hoot/control/conflicts/map/FeatureHighlighter.js
@mingjiesu will merge https://github.com/ngageoint/hootenanny/issues/136 into hoot develop which is needed for this pull.
=> Issue #450 : handle variable numbers of relation members

js/id/ui/map_metadata.js
tab separated instead of comma separated though
mime-type should make it open in spreadsheet software
=> #482, make the stats info downloadable

data/core.yaml, data/presets.yaml, data/presets/presets.json, dist/locales/en-GB.json, dist/locales/en.json
@mattjdnv Can you review the translations added to make sure they are kosher?
@mikejeffe Can you review wording of the new Save tool tip?
If you both just post a :+1:, I can take care of merge.  Thanks!
=> #504 Change Save Tool Tip Message

css/app.css, js/hoot/control/Conflate.js, js/hoot/control/conflate/AdvancedOptions.js, js/hoot/control/conflate/advanced_options/FieldsGenerator.js, js/hoot/control/conflate/advanced_options/FieldsetLogic.js
- Show selected advanced options as "Custom ...": https://github.com/ngageoint/hootenanny-ui/issues/429
- Add the element cache options to advanced UI settings: https://github.com/ngageoint/hootenanny-ui/issues/409
- Advanced Options CSS Updates: https://github.com/ngageoint/hootenanny-ui/issues/486
=> Advanced Conflation Options Updates

js/hoot/Hoot.js, js/id/renderer/arrow_layer.js
so it's not blocked by map features
=> #372 move merge arrow div to front when visible

js/hoot/view/utilities/Utilities.js
The logo can now close the Manage tab and bring the user back to the map
Ticket: #516
=> Give logo same functionality as Return to Map

css/app.css, js/id/ui.js
Created a feature branch off of `develop` instead of `master`
Ticket: #515
=> #515: Add min and max width to sidebar

js/hoot/control/utilities/Folder.js
added keypress function to input for add folder (same code as onclick).
=> hitting enter adds folder instead of refreshing

js/id/ui/map_metadata.js
refs https://github.com/DigitalGlobe/VGI-team-repo/issues/182
also add label when ref or secondary layer is missing
=> make stats display backwards compatible

js/hoot/control/utilities/Folder.js
#567 
Checks number of loaded layers before building context menu
=> Context Menu Fix

js/id/renderer/map.js, js/id/svg/layers.js
The highlight function is now called anytime `redraw` is called or anytime `drawLayers` in `Layers.js` is called
Ticket: #571
=> 571 - Disappearing Highlight

css/app.css
Ticket: https://github.com/ngageoint/hootenanny-ui/issues/576
=> Remove important from add-point css class

js/hoot/model/Export.js, js/hoot/model/Import.js
UI portion form #521 to support OSM schema for export
=> #521 IMPORT/EXPORT Path for OSM

js/hoot/ui/HootFormReviewNote.js
Same testing flow as https://github.com/ngageoint/hootenanny-ui/pull/615
=> Remove duplicate code causing multiple user icons

js/hoot/model/rest.js
refs https://github.com/ngageoint/hootenanny/pull/971
=> Add UI handler for F_CODE = Not found

js/hoot/control/Import.js, js/hoot/model/rest.js, js/id/ui/preset_list.js, js/id/ui/raw_tag_editor.js
=> support port or path in nodejs server port config

js/hoot/control/Export.js, js/hoot/control/utilities/ExportDataset.js, js/hoot/control/utilities/ImportDataset.js, js/hoot/model/Export.js
=> Issue 475: Expose pbf as available import/export format

js/hoot/control/Validation.js, js/id/ui.js
This should adjust back to the initial size of 400px.
I also fixed an issue where text wasn't properly moving when the sidebar was expanded
=> Fix sidebar double click

js/id/ui/preset.js
The UI field is now removed when clicking the trash can icon
Ticket: #647
=> #647: Cannot remove added field to feature

js/hoot/control/conflate/AdvancedOptions.js
Noticed the issue when testing for the background randomizer
=> Remove _modalBackground error to fix eslint issue

js/hoot/control/utilities/BulkImportDataset.js, js/hoot/control/utilities/ImportDataset.js
=> Allow all translations for OSM

js/hoot/control/utilities/BulkImportDataset.js, js/hoot/control/utilities/ImportDataset.js
https://github.com/ngageoint/hootenanny-ui/issues/141
https://github.com/ngageoint/hootenanny/pull/1048
=> Issue #141  Ingest geonames file with .txt extension

js/hoot/tools.js
=> Show map when loading review layer

js/hoot/model/Folders.js
=> Delete selected folder, not siblings

data/core.yaml, dist/locales/en.json, js/id/ui/map_data.js
This code is already in iD and is being added because of it's high priority
Ticket: #734
=> Add iD code for toggle all Map Features

js/hoot/tools.js
refs https://github.com/ngageoint/hootenanny/issues/1068
=> Add ability to run OSM API db conflation with a Tasking Manager grid bounds

js/hoot/control/Conflate.js, js/hoot/control/Control.js, js/hoot/control/View.js
#694 
To make sure this works:
1. add 2 datasets
2. make some edits
3. do not save them
4. press "conflate"
you should see an error alert pop up that warns you to save your edits before conflating.
Then you can either save or undo the edits and conflation should work.
Thanks @sisskind for your assistance :smile:
=> #694 check for unsaved edits before conflating

css/style2.css, js/hoot/control/Import.js
=> Fix CSS issue in Firefox

css/style2.css, index.html, js/hoot/control/utilities/BulkImportDataset.js, js/hoot/control/utilities/ImportDataset.js, js/hoot/control/utilities/ImportDirectory.js, js/hoot/control/utilities/Utilities.js, js/hoot/model/Import.js, js/hoot/ui/HootFormBase.js, js/hoot/view/utilities/Dataset.js, test/index.html
Ability to import individual shapefiles or OSM files from a directory in bulk fashion.
@brianhatchl already have a ticket to create a cucumber test (#771)
=> Import directory with individual files

js/hoot/control/utilities/BulkImportDataset.js, js/hoot/control/utilities/ImportDirectory.js
Bulk import improvements (#300)
=> #300 Bulk Import Improvements

js/id/renderer/background.js, js/id/services/dgservices.js, js/id/ui/background.js
add dns aliases for gbm host
add support for connect id prompt for egd
fix a bug with DG Collection overlay
=> updates for dg-plugin

js/id/services/dgservices.js
also add switch support to wfs request (if dg services ever
support CORS)
=> use proxy host for egd to avoid basic auth issues

js/id/id.js
=> Translation function created and called in copy function in iD

Makefile, index.html, js/hoot/control/Conflate.js, js/hoot/model/Export.js, js/hoot/model/Layers.js, js/hoot/model/rest.js, js/id/behavior/hash.js, js/lib/d3.v3.js
Changes needed by tasking manager integration with Hoot
=> Export osmapidb

css/hoot-style.css
=> Tag table transparency and border fixed

Makefile, build.js, dist/index.html, index.html, js/id/id.js, js/id/services/dgservices.js, package.json, test/index.html
refs #806 
fixes some eslint warnings and re-enables the tests on the dist build artifacts.
=> fix dist build & tests

js/hoot/view/utilities/Utilities.js
=> Remove NGA Research

js/hoot/control/conflate/advanced_options/SelectionRetriever.js
https://github.com/ngageoint/hootenanny-ui/issues/644
=> Update cplusEnabled for adv. opts.

js/hoot/control/conflicts/actions/PoiMerge.js, js/hoot/control/conflicts/map/FeatureHighlighter.js, js/hoot/control/conflicts/map/ReviewArrowRenderer.js
=> enable merge button for poi-to-polygon reviews

js/hoot/tools.js, js/id/svg/tag_classes.js
=> when input source metadata map id is unavailable, use hoot:status

js/id/core/connection.js, js/id/modes/save.js
* Previous code checked newWays length with vis.length to change go, but not sure why.  Changed to throw error if vis.length !== 1.
#787
=> Error message resurrected when trying to save with 2 layers present

js/hoot/model/Layers.js
=> set 'id' too (it's not set for conflation result layers)

js/id/renderer/features.js, js/id/renderer/map.js
add review features (points) back in if they get filtered out
refs #824
=> allow map feature filtering in review mode

js/hoot/control/Conflate.js
=> Add advanced options label under Conflate

js/hoot/control/Conflate.js
Label stays where it's supposed to now :see_no_evil:
=> Fix Advanced Options Label

js/id/renderer/map.js, js/id/ui/background.js
=> fix zoom to basemap

css/style2.css, js/hoot/model/rest.js, js/id/ui/alert.js
Errors/progress/success messages should display with these changes, but including further details about Hoot core commands has been pushed to another ticket inside a new UI error handling Epic.
=> Update alert div to handle formatting for UI errors, read in error output from back-end

js/id/ui/entity_editor.js, js/id/ui/raw_tag_editor.js
=> ignore tag changes where key or value is ''

js/hoot/model/Conflicts.js, js/id/svg/tag_classes.js
=> code now handles code & text versions of hoot:status

js/hoot/control/conflicts/actions/TraverseReview.js, js/hoot/control/conflicts/map/FeatureHighlighter.js
=> fixes for bugs re: review relations with more than two members

js/id/core/connection.js
=> remove UI generated hoot:layername tag

js/hoot/control/Export.js, js/hoot/control/utilities/BulkImportDataset.js, js/hoot/control/utilities/ExportDataset.js, js/hoot/control/utilities/ImportDataset.js, js/hoot/control/utilities/ImportDirectory.js
Make the labels for the dropdowns for the translation more descriptive for the user.
=> Update Translation Labels

js/id/services/dgservices.js
=> no longer proxy wfs request, CORS enabled

js/hoot/control/utilities/Translation.js
=> Translation paste issue

js/hoot/control/utilities/Translation.js
Reverts ngageoint/hootenanny-ui#907
=> Revert "Translation paste issue"

js/id/services/dgservices.js
=> Translation Drag and Drop

js/hoot/control/utilities/Translation.js, js/hoot/view/utilities/Translation.js
Export existing translation to .js file
=> Export translation

js/hoot/control/Export.js, js/hoot/control/utilities/ExportDataset.js
Change 'Export Status as Text' to 'Include Hoot Status Field'
=> Rename export as text

Makefile, css/style2.css, index.html, js/hoot/control/utilities/BulkExportDataset.js, js/hoot/control/utilities/Folder.js, js/hoot/control/utilities/Utilities.js, js/hoot/model/Export.js, js/hoot/model/Folders.js, js/hoot/tools.js, js/hoot/view/utilities/Dataset.js, test/index.html
- https://github.com/ngageoint/hootenanny-ui/issues/919
- https://github.com/ngageoint/hootenanny-ui/issues/920
=> Bulk export tool

js/id/ui.js, js/id/ui/coordinates.js
Allow user to switch to MGRS coordinates like in MapEdit
https://github.com/DigitalGlobe/VGI-team-repo/issues/798
=> Add MGRS conversion and update UTM formatting

Makefile
=> remove source file wildcards

js/hoot/Hoot.js, js/hoot/control/utilities/BulkExportDataset.js, js/hoot/control/utilities/BulkImportDataset.js, js/hoot/model/rest.js, js/hoot/view/utilities/Translation.js, test/index.html, test/index_packaged.html, test/spec/hoot.js, test/spec/hoot/model/export.js
Straightforward - same as Bulk Import #935
=> Improve Bulk Export Form and Differentiate Translations

js/hoot/model/Export.js
path is included in config property
=> fix default export translation

css/style2.css
=> 897 stack alerts vertically

js/hoot/control/Conflate.js
refs https://github.com/ngageoint/hootenanny/issues/2038
=> Add 'Differential' as a conflation type, not a road engine

js/id/ui/map_metadata.js
refs https://github.com/ngageoint/hootenanny/issues/2084
=> Add section for differential conflation to stats panel

data/hootConfig.json, js/id/services/translationserver.js
=> by by levenshtein, sad to see you go

js/hoot/control/utilities/BulkExportDataset.js, js/hoot/control/utilities/ExportDataset.js, js/hoot/control/utilities/SetTagOverrides.js, js/hoot/model/Export.js
=> Strip hoot tags and review relations by default on osm export

js/hoot/tools.js
=> Fix bug setting Attribute Reference Layer in conflation

css/app.css, js/hoot/control/utilities/Folder.js, js/hoot/control/utilities/ImportDataset.js, js/hoot/control/utilities/Translation.js, js/hoot/model/Export.js, js/hoot/model/Folders.js, js/hoot/model/Layers.js, js/hoot/model/rest.js, js/hoot/view/utilities/Dataset.js, js/hoot/view/utilities/Translation.js, js/hoot/view/utilities/Utilities.js, js/id/core/connection.js, js/id/ui/alert.js, js/id/ui/coordinates.js
Issue https://github.com/ngageoint/hootenanny-ui/issues/1233
Pairs w/ https://github.com/ngageoint/hootenanny/pull/2682
=> refactor map resource methods

dist/locales/en.json, dist/login.html, modules/Hoot/login.js, modules/Hoot/managers/api.js, modules/Hoot/managers/layerManager.js, modules/Hoot/managers/translationManager.js, modules/Hoot/ui/conflicts/conflicts.js, modules/Hoot/ui/conflicts/merge.js, modules/Hoot/ui/sidebar/sidebar.js, modules/services/osm.js, modules/ui/entity_editor.js, package-lock.json, package.json, webpack-config/webpack.dev.config.js
=> show conflation review UI when entering review mode

js/hoot/control/Conflate.js, js/hoot/control/conflate/advanced_options/FieldsRetriever.js, js/hoot/control/conflate/advanced_options/FieldsetLogic.js, js/hoot/model/rest.js
refs #1276 and https://github.com/ngageoint/hootenanny/issues/2842
=> Add "Attribute" conflation type

modules/Hoot/config/domMetadata.js, modules/Hoot/ui/sidebar/layerConflate.js
=> Removing generate report conflate option from sidebar

js/hoot/control/Conflate.js, js/hoot/control/conflate/advanced_options/FieldsRetriever.js, js/hoot/model/Conflate.js, js/hoot/model/rest.js, js/hoot/tools.js, js/hoot/view/utilities/About.js
and also generate report artifacts
refs #1301
=> remove Average conflation type

modules/Hoot/config/domMetadata.js, modules/Hoot/ui/sidebar/layerConflate.js
Sets attribute reference  to secondary layer in a sidebar when conflating
=> Set default Attribute refrence to secondary layer

js/hoot/control/Conflate.js
=> Default attribute reference to secondary layer for Attribute conflation

css/hoot/modules/_forms.scss, karma.conf.js, modules/Hoot/config/domMetadata.js, modules/Hoot/tools/formFactory.js, modules/Hoot/ui/managePanel/translations.js, modules/Hoot/ui/modals/addTranslation.js, modules/Hoot/ui/modals/viewTranslation.js
ref https://github.com/ngageoint/hootenanny-ui/issues/1322
=> View Translation Files

modules/ui/schema_switcher.js
=> remove console log

css/hoot/modules/_alerts.scss, modules/Hoot/managers/api.js, modules/Hoot/ui/managePanel/datasets.js
=> show error message when trying to delete other user's resource #1336

css/hoot/modules/_forms.scss, modules/Hoot/config/domMetadata.js, modules/Hoot/managers/api.js, modules/Hoot/managers/folderManager.js, modules/Hoot/tools/folderTree.js, modules/Hoot/tools/formFactory.js, modules/Hoot/ui/modals/addFolder.js, modules/Hoot/ui/modals/modifyDataset.js, modules/Hoot/ui/modals/modifyFolder.js, test/hoot/spec/datasetPanel/tableBehavior.js
=> Add folder visibility to Add, Modify, and row rendering

.gitignore, modules/Hoot/config/buildInfo.json, modules/Hoot/hoot.js, package.json, webpack-config/webpack.base.config.js
will have to be updated manually with 'npm run buildinfo'
=> restore buildInfo.json to fix rpm builds

modules/behavior/draw_measure_area.js, modules/behavior/draw_measure_line.js, modules/core/context.js, modules/ui/scale.js
=> update/share current units between scale/measure tools via context

modules/Hoot/config/domMetadata.js, modules/Hoot/managers/api.js, modules/Hoot/ui/managePanel/datasets.js, modules/Hoot/ui/managePanel/translations.js, modules/Hoot/ui/modals/ImportMultiDatasets.js, modules/Hoot/ui/modals/importDataset.js
ref #1333
@brianhatchl defaults now show up first in import modal, custom translations after the default list
=> added method to sort translations, defaults first, custom after

data/imagery.json, js/hoot/control/utilities/ClipDataset.js, js/hoot/model/Folders.js, js/hoot/model/rest.js, js/hoot/view/utilities/Dataset.js
=> update clip to send FOLDER_ID as parameter

modules/Hoot/managers/folderManager.js, modules/Hoot/ui/managePanel/datasets.js
=> add dataset pane button to toggle public data visibility

js/id/ui/modes.js
=> Fixed #1005. fixed toggle off for tools using shortcut

modules/renderer/map.js, modules/services/osm.js
refs #1420
also reverts some map code to be more like upstream iD
=> fix tile id to use both id and map id

modules/Hoot/ui/managePanel/jobs.js, modules/Hoot/ui/modals/jobCommandInfo.js
=> Fixed #1419. polling will now stop when the modal is closed

modules/Hoot/ui/modals/ImportMultiDatasets.js
=> GeoJSON now an upload option w/in Import Muti Dataset modal

modules/Hoot/managers/layerManager.js, modules/Hoot/ui/sidebar/layerAdd.js, modules/Hoot/ui/sidebar/sidebar.js, modules/services/osm.js, modules/svg/helpers.js, modules/svg/lines.js, modules/svg/vertices.js, modules/ui/background.js
=> 1408. added dataset toggle + button to switch which layer is on top

modules/Hoot/managers/layerManager.js, modules/Hoot/tools/clipDataset.js, modules/Hoot/ui/modals/importDataset.js, modules/Hoot/ui/sidebar/layerConflate.js, test/index.html, test/spec/Hoot/managers/layerManager.js
=> added check for layer name, if it exists, append a number to end of name

modules/Hoot/ui/modals/jobCommandInfo.js, test/hoot/spec/datasetPanel/tableBehavior.js
=> 1426. job command details modal should only show status logs

modules/Hoot/managers/api.js, modules/Hoot/ui/modals/ImportMultiDatasets.js, modules/Hoot/ui/modals/importDataset.js
=> ui will set parent id for ingest job in 1 request now

modules/Hoot/managers/api.js, modules/Hoot/ui/managePanel/jobs.js, modules/Hoot/ui/modals/exportData.js, modules/Hoot/ui/modals/jobCommandInfo.js, modules/util/detect.js
also remove some logging and handle a 403 in job status req
fixes #1446
=> Don't offer view log for running jobs owned by others

js/hoot/model/rest.js, js/hoot/tools.js, js/hoot/view/utilities/Dataset.js
=> removes sizes api call since it is a part of layers now

dist/locales/en.json, modules/Hoot/managers/folderManager.js, modules/Hoot/ui/modals/modifyDataset.js, package-lock.json
=> Move maps to folders by id

modules/Hoot/managers/api.js, modules/Hoot/ui/modals/modifyDataset.js, modules/Hoot/ui/modals/modifyFolder.js
when a 403 forbidden is returned
=> improve error messages when trying to modify datasets & folders

modules/Hoot/config/domMetadata.js, modules/Hoot/ui/modals/ImportMultiDatasets.js, modules/Hoot/ui/modals/exportData.js, modules/Hoot/ui/modals/importDataset.js
=> Allow for import/export of GeoPackage

css/hoot/components/_navbar.scss, modules/Hoot/ui/navbar.js
=> updated css & navbar to show dropdown when managePanel is visible

modules/behavior/clip.js
=> corrected clip coordinates min/max values

modules/Hoot/ui/modals/ImportMultiDatasets.js, modules/Hoot/ui/modals/exportData.js, modules/Hoot/ui/modals/importDataset.js
Old error popup:
New error popup:
=> show more detailed error message when importing/exporting

modules/Hoot/ui/modals/jobCommandInfo.js
=> Fixed #1452. stopped polling on finished job when detail modal is open

modules/Hoot/ui/modals/importDataset.js
=> use correct property

modules/Hoot/managers/layerManager.js, modules/Hoot/ui/conflicts/map.js
=> update zooms for reviews so they are bound to level 16 and 21 and handle layer query param

modules/Hoot/ui/conflicts/info.js, modules/Hoot/ui/conflicts/map.js
=> Zoom to review feature on tag-table click

dist/login.html, modules/Hoot/login.js
=> working on updating login

modules/Hoot/managers/layerManager.js, modules/Hoot/ui/sidebar/sidebarController.js
=> do not allow undefined in hash, make hash match loadedLayers state

css/hoot/components/managePanel/_datasets.scss
=> make dataset table bigger

modules/Hoot/managers/api.js, modules/Hoot/ui/conflicts/resolve.js
=> adding 'resolveall' method to api

modules/Hoot/managers/api.js, modules/behavior/draw_measure_area.js, modules/behavior/draw_measure_line.js, modules/modes/add_measure_area.js, modules/modes/add_measure_line.js, modules/ui/modes.js, modules/ui/tools.js
=> Fixing up measure tool behaviors

modules/Hoot/ui/managePanel/datasets.js, modules/Hoot/ui/managePanel/jobs.js, modules/Hoot/ui/managePanel/translations.js, modules/Hoot/ui/modals/importDataset.js
=> Translation Assistant workflow fixes

modules/Hoot/managers/api.js
=> migrate user path to api/0.6

modules/Hoot/ui/sidebar/layerAdd.js
=> increased  maxListeners limit

css/hoot/components/_conflicts.scss
=> can now interact with map below conflict table horizon

modules/Hoot/ui/managePanel/jobs.js, modules/ui/tools.js, test/hoot/index.js
=> hide grail tools for non advanced users

modules/Hoot/managers/api.js
=> convert setInterval to setTimeout in job status polling

modules/Hoot/managers/api.js
=> Fixed #1520.For grail pull use error message from api if one is provided

modules/Hoot/ui/sidebar/layerMetadata.js
=> add stats and download to conflated layers' info sections

modules/Hoot/ui/sidebar/layerReview.js
=> add click handlers to buttons in complete review.

modules/Hoot/login.js
=> Prevent infinite login loop

modules/Hoot/tools/folderTree.js
=> added additional check for formMeta then form

modules/Hoot/managers/api.js, modules/Hoot/ui/managePanel/jobs.js
=> add ability to save changeset osc file

dist/locales/en.json, modules/Hoot/managers/api.js, modules/Hoot/tools/differentialUpload.js, modules/Hoot/tools/selectBbox.js, modules/Hoot/ui/managePanel/jobs.js, modules/Hoot/ui/modals/differentialStats.js, modules/ui/tools.js
=> Fixed #1524. stale data prevents changest upload and derive

css/hoot/modules/_forms.scss, modules/Hoot/managers/api.js, modules/Hoot/tools/grailPull.js, modules/Hoot/ui/modals/differentialStats.js
=> Fixed #1532. Added estimate for grail pull overpass data

modules/Hoot/tools/clipDataset.js
=> default output folder now the same as layer that will be clipped
