ngageoint/hootenanny-ui

js/hoot/tools.js
* ngageoint/hootenanny-ui#253
Changed the 'if statement' to assume that if there are no active reviews, there is no reason to go into review mode.  It seemed that there were times where the code would jump to this statement before the user could determine if they wanted to go into review mode.  If the user does not decide to go into review mode, the same code is run.  
This is a duplication (lines 531-540 and 547-557) and can be adjusted, but wanted to get this fixed before cutting the release.  Will also push into release branch once this pull request is closed.
=> Layer containing unresolved reviews get's loaded twice in UI

js/id/operations/review.js
Should not allow user to traverse to new review using GoTo Review if there are outstanding changes.
=> #451 Prevent moving to review if there are outstanding changes

js/hoot/plugins/EntityEditor.js
the return var is never used (eslint complaint) but the function
called modifies member data properties, so needs to be invoked.
=> #473, fix something eslint broke

js/id/renderer/background.js, js/id/ui/background.js
This turns on/off the labels layer when it is needed/not necessary. Users can still manually toggle it on/off if they would like.
Ticket: #518
=> #518: Disable the locator overlay when switching away from Satellite imagery

css/base.css, css/style2.css
There was a max width that was preventing the inputs from expanding all the way, so that has been removed and matched to the sidebar code from #515 
Ticket: #523
=> #523: Expanding width of left frame needs improvement

js/hoot/control/utilities/ImportDataset.js
New pull request with develop as base. Uncommented code that shows spinner icon when importing dataset. Commented out code that triggers progress bar. Now only the spinner will show up to the right of "Import" button when you click it.
=> 545 updated: replaced loading bar with spinner icon for dataset import

js/hoot/control/View.js
If a user is in the `draw-line` or `draw-area` mode, they will be prompted when clicking the trash can icon to finish their drawing before deleting the layer.
Ticket: #588
=> 588 - Prompt users to finish drawing before deleting a layer

js/id/core/connection.js
Add code to prevent features from disappearing. If all works as planned, then if you draw a feature, then zoom in past z16, then zoom out, the feature should still be there. Workflow can be found [here](https://github.com/ngageoint/hootenanny-ui/issues/546).
Ticket: https://github.com/ngageoint/hootenanny-ui/issues/546
=> Give variable to context.flush() in connection.js

js/hoot/control/utilities/BulkImportDataset.js
When you do a bulk import a spinner icon will indicate uploading rather than a progress bar (right click on add dataset to access bulk import).
=> #598 added spinner to indicate loading import; removed progress bar

js/hoot/tools.js
Appears that the second call to getMapTags never returned a response on the second call (called twice to determine if in review mode).  Adjusted the handleLayer function to pass in tags object to avoid second call.
@brianhatchl When you are reviewing, can you make sure that the Validation calls are working as well?
=> #607 Merged layer loads out of review mode

css/app.css
This is the change
Before:
After:
(#623)
=> 623 Fixed borders in help menu

css/app.css, js/hoot/view/utilities/Translation.js
On translations page you should see just the shortname of the translation and a tooltip of the description / longer name when you hover.
For some reason setting the opacity is bumping down the trashcan icon. I removed it for now. Not sure if it's necessary (or having a trashcan is necessary? I'm not sure if there's a case in which someone would choose to remove a translation). If we want to make the trashcans more transparent again I can look further into this.
=> #586 added tooltips for translation descriptions

js/id/renderer/map.js
#560 
By removing the shadow class on map move, the delayed shadow drawing no longer occurs.  This line had been commented out, but cannot find supporting evidence as to why.
=> #560 Removing shadow on map move

js/id/renderer/map.js
When Hoot is opened in a minimized window, it should now scale accordingly when the window is maximized or dragged to the desired size.
Ticket: #538
=> Map now re-renders when window is resized.

js/hoot/control/utilities/Folder.js, js/hoot/view/utilities/Utilities.js
If you return to map with the context menu still up it should now disappear :dash:
**To repeat:** 
1. Open hoot, click on manage tab
2. Right click on a dataset, any dataset!
3. Click "Return to map." Context menu should go away.
See ngageoint/hootenanny-ui#627
=> 627: context menu hanging

js/hoot/view/utilities/Utilities.js
Extension of #627. 
Fixed context menu hanging for **Tools menu**:
1. Click tools, navigate over one of the options so the second menu pops up.
2. Click "Manage" button. Context menus should disappear.
and **Bulk Import**:
1. Click on "Manage" button.
2. On datasets menu, right click "Add Dataset" to show "Bulk Import" context menu.
3. Click "Return to Map." Context menu should disappear.
=> #741: fixes context menu hang for tools menu and bulk import

css/hoot-style.css
So I widened the columns, they default to the width in the image below (75px) when there's no data in the tag table. Let me know if this looks better than "N/A" as a placeholder.
=> Remove JS changes for tag table, adjust size of columns

css/style2.css, js/hoot/view/utilities/Utilities.js
When I added the new logo I did something silly which made the check version popup to not work.
So I fixed that, and changed the `hoot-logo` class to `hoot_label` so the check_version cuke test would pass :+1:
=> Check version Bug Fix with new logo

js/hoot/view/utilities/Dataset.js, js/id/services/dgservices.js
This is a feature used in holy grail tasking manager integration.  It attempts to create task grids that balance the number of nodes in the to-be-conflated dataset for each task.
=> generate kdtree tiles for conflation project task grids

js/hoot/model/Conflicts.js
this may be the true cause of
https://github.com/ngageoint/hootenanny/issues/1602
the intermittent failure probably depends on what review is loaded first
=> hoot:status may be undefined

css/login.css, dist/index.html, index.html
refs #1237
* add padding to bottom of login page
* pass back errors from popup window console to main window console for easier debugging
* fix issue w/ infinite refresh loop
* remove oauth params from address bar when they fail
=> bug fix: oauth: handle authentication failure gracefully

Jenkinsfile
Instead of compiling hootenanny to test the UI, we could install the latest RPM in the develop repository.  Once installed run UI tests against hoot install.  In theory, this should save time and cut down on unnecessary compiling.
=> Install hoot from RPM

modules/Hoot/tools/formFactory.js
most likely I should self git blame here, but the "sorting items" logic in the combobox factory was wrong :disappointed: 
This fixes that issue and its downstream 'I can't select other folders' issue @kweint found
Also should fix all cases of selecting folder since those comboboxes share the `path-name` class I'm using here
closes #1371
=> Fix import and most other combobox's sort logic

modules/Hoot/managers/layerManager.js, modules/Hoot/ui/conflicts/conflicts.js, modules/Hoot/ui/conflicts/traverse.js, modules/Hoot/ui/sidebar/layerReview.js
ref #1312
@brianhatchl I set reviewItem to null in traverse.js, it seems to have resolved the issue with finding the layer ids.
=> layer review ui removed when layer deleted

modules/Hoot/managers/layerManager.js, modules/Hoot/ui/conflicts/conflicts.js, modules/Hoot/ui/conflicts/graphSync.js, modules/Hoot/ui/conflicts/traverse.js
refs #1506
The crux of the issue addressed is the map needs to be
zoomed to an editable extent before the UI can go into
review mode.  So get an initial review item (which now
supplies it's extent) and zoom the map.  Then instead of
loading a new review item we have a new method to
show the initial review item zoomed to.
=> get initial review extent from review item

css/hoot/components/_clip.scss, modules/Hoot/tools/selectBbox.js, modules/svg/data.js
specifically, task bounds provided in a gpx file via querystring parameter.
To test, unzip this file 
[example.gpx.zip](https://github.com/ngageoint/hootenanny-ui/files/3437444/example.gpx.zip)
in your `dist/` folder and open this url:
http://localhost:8080/#background=Bing&disable_features=boundaries&gpx=example.gpx&map=13.07/18.5246/-72.4554
=> Allow custom data extent to be used in bbox operations (clipping, grail, etc)
